/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codeflow

import codeflow.java.AstReader
import java.nio.file.FileVisitOption
import java.nio.file.Files
import java.nio.file.Path

fun main(args: Array<String>) {
    val javaRootDir = args.first { !it.startsWith("--") }
    // Source paths come back from javac as absolute URIs, and AstReader relativizes them
    // against this one. Path.relativize throws if only one of the two is absolute.
    val javaRootDirPath = Path.of(javaRootDir).toAbsolutePath().normalize()

    val filesPaths = generateListOfJavaFilesFromDir(javaRootDirPath)
    val mainMethod = AstReader(javaRootDirPath).process(filesPaths)

    val result = ArrayList<String>()
    // Both renderings go to stdout, which is the document; the diagnostics AstReader prints are on
    // stderr, so redirecting stdout to a file gives something a viewer can open directly.
    if (args.contains("--json")) {
        JsonExporter().processMainMethod(mainMethod) { result.add(it) }
    } else if (args.contains("--graphml")) {
        GraphmlExporter().processMainMethod(mainMethod) { result.add(it) }
    } else {
        MermaidExporter().processMainMethod(mainMethod) { result.add(it) }
    }

    result.forEach { println(it) }
}

fun generateListOfJavaFilesFromDir(dir: Path): List<Path> {
    return Files.walk(dir, FileVisitOption.FOLLOW_LINKS)
        .filter { it.toString().endsWith(".java") }
        .toList()
}
