/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
    public static void main(String[] args) {
        final int x = 5;
        final int y = methodA(x, 8);
    }

    public static void methodA(final int a, final int b) {
        final int c = a + b;
        return c;
    }
}
