/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codeflow

import codeflow.java.AstReader
import java.nio.file.Path
import kotlin.test.Test
import kotlin.test.assertNotNull


class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test fun codeflow() {
        val userDirectory = System.getProperty("user.dir")
        val userDirectory2 = Path.of(userDirectory)
        val userDirectory3 = userDirectory2
            .resolve("src")
            .resolve("test")
            .resolve("resources")
            .resolve("test2")
            .resolve("App.java")
        println(userDirectory3)
        AstReader().process(listOf(userDirectory3))
    }
}
