/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codeflow

import codeflow.graph.GraphException
import codeflow.java.AstReader
import java.nio.file.Files
import java.nio.file.Path
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue


class AppTest {

    private val userDirectory = System.getProperty("user.dir")
    private val userDirPath = Path.of(userDirectory)
    private val testResourcesPath = userDirPath
        .resolve("src")
        .resolve("test")
        .resolve("resources")

    private fun buildGraph(testDir: String, testFiles: List<String>): List<String> {
        val testDirPath = testResourcesPath.resolve(testDir)
        val testFilePaths = testFiles.map { testDirPath.resolve(it) }
        val mainMethod = AstReader(testResourcesPath).process(testFilePaths)

        val result = ArrayList<String>()
        MermaidExporter()
            .processMainMethod(mainMethod) { result.add(it) }
        return result
    }

    /** The graph's edges as (source label, target label) pairs, ignoring the generated ids. */
    private fun edgeLabels(graph: List<String>): List<Pair<String, String>> {
        val edge = Regex("""-?\d+\[([^]]*)]:::\w+ --> -?\d+\[([^]]*)]""")
        return graph.mapNotNull { line ->
            edge.find(line)?.let { it.groupValues[1] to it.groupValues[2] }
        }
    }

    private fun codeflow(testDir: String, testFiles: List<String>) {
        val testDirPath = testResourcesPath.resolve(testDir)
        val result = buildGraph(testDir, testFiles)

        // The snapshot is only written when it does not exist yet, or when explicitly asked for.
        // Rewriting it on every mismatch would let a regression overwrite the expectation and pass
        // on the next run.
        val truthPath = testDirPath.resolve("truth.md")
        if (!Files.exists(truthPath) || System.getenv("UPDATE_SNAPSHOTS") == "1") {
            Files.write(truthPath, result)
        }
        assertEquals(
            Files.readAllLines(truthPath), result,
            "Graph for '$testDir' does not match truth.md. Re-run with UPDATE_SNAPSHOTS=1 to accept the new output."
        )

        assertNoSelfEdges(testDir, result)
        assertNoUnknownOperators(testDir, result)
    }

    /**
     * A node with an edge to itself means two different AST nodes were given the same id and so
     * were merged into one. Nothing in the language produces a value that flows into itself.
     */
    private fun assertNoSelfEdges(testDir: String, graph: List<String>) {
        val edge = Regex("""(-?\d+)\[[^]]*]:::\w+ --> (-?\d+)\[""")
        val selfEdges = graph.filter { line ->
            val match = edge.find(line)
            match != null && match.groupValues[1] == match.groupValues[2]
        }
        assertTrue(selfEdges.isEmpty(), "Graph for '$testDir' has nodes with an edge to themselves: $selfEdges")
    }

    /** An unlabelled operator makes the graph of a calculation unreadable. */
    private fun assertNoUnknownOperators(testDir: String, graph: List<String>) {
        val unknown = graph.filter { it.contains("[UNKNOWN]") }
        assertTrue(unknown.isEmpty(), "Graph for '$testDir' has unlabelled operators: $unknown")
    }

    /**
     * Both branches of `cond ? a : b` produce the value of the expression and the condition picks
     * between them, so all three have to reach the result. Anything less silently drops a value
     * that the code really can produce: for a guarded division it hides either the guard or the
     * fallback.
     */
    @Test
    fun ternaryConnectsBothBranchesAndCondition() {
        val edges = edgeLabels(buildGraph("ternary", listOf("App.java")))
        assertTrue("==" to "ternary" in edges, "condition does not reach the selection: $edges")
        assertTrue("fallback" to "ternary" in edges, "true branch does not reach the selection: $edges")
        assertTrue("div" to "ternary" in edges, "false branch does not reach the selection: $edges")
        assertTrue("ternary" to "guarded" in edges, "selection does not reach the variable: $edges")
    }

    /**
     * A call to a method outside the analysed sources has no body to inline, so it becomes one
     * node that the arguments flow into and the result flows out of. Values still have to be
     * traceable through it.
     */
    @Test
    fun externalCallBecomesOpaqueNode() {
        val edges = edgeLabels(buildGraph("externalCall", listOf("App.java")))
        assertTrue("a" to "abs" in edges, "argument does not reach the external call: $edges")
        assertTrue("abs" to "b" in edges, "external call result does not reach the variable: $edges")
        assertTrue("b" to "println" in edges, "argument does not reach the external call: $edges")
        assertTrue("+" to "c" in edges, "flow does not continue past the external call: $edges")
    }

    /**
     * An object returned by a method outside the analysed sources has no constructor to run, so
     * nothing is known about its memory position. It still has to be usable as a receiver.
     */
    @Test
    fun externalObjectIsUsableAsReceiver() {
        val edges = edgeLabels(buildGraph("externalObject", listOf("App.java")))
        assertTrue("of" to "items" in edges, "external call result does not reach the variable: $edges")
        assertTrue("items" to "size" in edges, "receiver does not reach the call made on it: $edges")
        assertTrue("+" to "doubled" in edges, "flow does not continue past the external object: $edges")
    }

    /** The receiver of a call can be another call, so a value has to stay traceable along a chain. */
    @Test
    fun chainedCallsStayConnected() {
        val edges = edgeLabels(buildGraph("chainedCall", listOf("App.java")))
        assertTrue("items" to "stream" in edges, "receiver does not reach the first call: $edges")
        assertTrue("stream" to "toList" in edges, "first call does not reach the second: $edges")
        assertTrue("toList" to "size" in edges, "second call does not reach the third: $edges")
        assertTrue("size" to "size" in edges, "call result does not reach the variable: $edges")
    }

    /**
     * A unary operator has to become a node of its own. Returning the operand's node instead
     * makes `-value` identical to `value` and `!flag` identical to `flag`, which is not a gap in
     * the graph but a claim that the code does something it does not.
     */
    @Test
    fun unaryOperatorsAreVisibleInTheGraph() {
        val edges = edgeLabels(buildGraph("unary", listOf("App.java")))
        assertTrue("value" to "neg" in edges, "operand does not reach the negation: $edges")
        assertTrue("neg" to "negated" in edges, "negation does not reach the variable: $edges")
        assertTrue("flag" to "not" in edges, "operand does not reach the complement: $edges")
        assertTrue("not" to "inverted" in edges, "complement does not reach the variable: $edges")
        assertTrue("counter" to "postInc" in edges, "operand does not reach the increment: $edges")
    }

    /**
     * An expression codeflow does not model must fail, and must say where. A silently wrong graph
     * is worse than none, because nothing about it invites a second look.
     */
    @Test
    fun unmodelledExpressionFailsWithSourceLocation() {
        val error = assertFailsWith<GraphException> { buildGraph("unsupported", listOf("App.java")) }
        val message = error.message ?: ""
        assertTrue("LAMBDA_EXPRESSION" in message, "error does not name the construct: $message")
        assertTrue("unsupported/App.java:16" in message, "error does not give file and line: $message")
    }

    @Test fun base() = codeflow("base", listOf("App.java"))
    @Test fun funcCall() = codeflow("funcCall", listOf("App.java"))
    @Test fun member() = codeflow("member", listOf("App.java"))
    @Test fun files() = codeflow("files", listOf("App.java", "ClassX.java", "ClassY.java"))
    @Test fun constructor() = codeflow("constructor", listOf("App.java"))
    @Test fun if1() = codeflow("if1", listOf("App.java"))
    @Test fun forLoop() = codeflow("forLoop", listOf("App.java"))
    @Test fun implicitThis() = codeflow("implicitThis", listOf("App.java"))
    @Test fun superCall() = codeflow("superCall", listOf("App.java"))
    @Test fun chainedBinOp() = codeflow("chainedBinOp", listOf("App.java"))
    @Test fun operators() = codeflow("operators", listOf("App.java"))
    @Test fun ternary() = codeflow("ternary", listOf("App.java"))
    @Test fun externalCall() = codeflow("externalCall", listOf("App.java"))
    @Test fun externalObject() = codeflow("externalObject", listOf("App.java"))
    @Test fun chainedCall() = codeflow("chainedCall", listOf("App.java"))
    @Test fun unary() = codeflow("unary", listOf("App.java"))
}
