/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
    public static void main(String[] args) {
        final int a = 5;
        final int b = a;
        final int c = b + 8;
        System.out.println(b);
    }
}
