/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
    public static void main(String[] args) {
        int a = 5;
        int b = a;
        if (b == 7) {
            b = 13;
        } else {
            a = 17;
        }
        final int c = b;
        final int d = a;
    }
}
