/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
    public static void main(String[] args) {
        int a = 5;
        int b = a;
        int f = 21;
        int c = 23;
        int d = 29;
        if (a == 7) {
            b = 13;
            f = b;
        } else {
            a = 17;
        }
        c = f;
        d = a;
    }
}
