/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {

    int memberA;
    public static void main(String[] args) {
        final int x = 5;
        memberA = x;
        final int y = memberA;
    }
}
