/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

class ClassX {
    public int memberX;
}

public class App {
    public static void main(String[] args) {
        final int x = 5;
        int y = 0;
        for (int i = 0; i < x; i++) {
            y = 7;
        }
        int z = y;

        y += 1;
    }
}
