/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package constructor;

class ClassParam {}

class ClassX {
    public int memberX;

    public ClassX(int v, ClassParam cp) {
        memberX = 7;
    }

    public ClassX(int initialValue) {
        memberX = initialValue;
    }

    public ClassX(int initialValue, String name) {
        memberX = initialValue;
    }
}

public class App {
    public static void main(String[] args) {
        ClassParam cp = new ClassParam();
        final ClassX x = new ClassX(5, cp);
        int b = x.memberX;

        final ClassX x2 = new ClassX(13, "test");
        int c = x2.memberX;
    }
}
