/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        final int a = 5;
        final int b = a + 8;
        System.out.println(b);
    }
}
